- _partials/intro.md
- Typo
- Confusing reference to "them"
> Quick review

- LINUX.md
- WINDOWS.md
- _partials/ubuntu_python.md
- macOS.md
Added extra pipx installs of `pytest` and `black` for Make to work without extra need for pyproject in every challenge
> added extra pipx requirements for new workflow

- LINUX.md
- WINDOWS.md
- _partials/kubernetes.md
- macOS.md
Adding the right hyperlinks to the k8s instructions 
https://github.com/lewagon/data-engineering-setup/issues/15
> Clarify kubernetes instructions

- LINUX.md
- WINDOWS.md
- _partials/ubuntu_docker.md
- macOS.md
Went through the set-up and have a few minor suggestions.
> docs: minor improvements

- LINUX.md
- WINDOWS.md
- _partials/virtual_machine.md
- macOS.md
A few more additions that I forgot to include in #20 😅
> docs: more minor improvements

- LINUX.md
- WINDOWS.md
- _partials/repo_overview.md
- _partials/ubuntu_python.md
- build.rb
- macOS.md
- Setup poetry `in-project=true` globally
- Add repo overview section to explain students what's happening under the hood :)
> add repo overview section and set poetry in-project true

- LINUX.md
- WINDOWS.md
- build.rb
- macOS.md
These are needed first thing for a REMOTE setup day. They should have already done it for the morning lecture, but just in case
> add zoom and slack at top of setup

- LINUX.md
- WINDOWS.md
- _partials/cli_tools.md
- macOS.md
line cut/pasted from 030201 readme
> add apt get mysql needed for 030201

- LINUX.md
- WINDOWS.md
- _partials/ubuntu_python.md
- macOS.md
- Removed pytest from pipx as conflicts with some tests
> remove pipx pytest as included in tomls

- LINUX.md
- WINDOWS.md
- _partials/repo_overview.md
- macOS.md
- added short section to fork and clone
> add thing about cloneing challenges

- LINUX.md
- WINDOWS.md
- _partials/dotfiles.md
- _partials/vscode_remote_ssh.md
- macOS.md
- small precision on local machine
- small precision on local machine
> rephrasing

- LINUX.md
- WINDOWS.md
- _partials/terraform.md
- _partials/ubuntu_docker.md
- _partials/ubuntu_python.md
- build.rb
- macOS.md
Just added section on terraform to setup! 
Fixes https://github.com/lewagon/data-engineering-setup/issues/19
> 2023 q2 updates

- LINUX.md
- WINDOWS.md
- _partials/vscode_remote_ssh.md
- macOS.md
> Typo correction

- LINUX.md
- WINDOWS.md
- _partials/cli_tools.md
- _partials/ubuntu_spark.md
- build.rb
- macOS.md
- add spark section
- add java
> linux spark

- LINUX.md
- WINDOWS.md
- _partials/ubuntu_spark.md
- macOS.md
Hey @ogiles1999, this follows an issue from the [Paris batch](https://lewagon-alumni.slack.com/archives/C05SV5CGJQL/p1696856909064579)
the teacher commented : "note the second element in the first command and the single quotes in the second one"
> correct spark install

- LINUX.md
- WINDOWS.md
- _partials/vscode_remote_ssh.md
- macOS.md
> more clarity for vscode remote ssh public IP address

- LINUX.md
- WINDOWS.md
- _partials/repo_overview.md
- macOS.md
> added clarity for direnv: error .envrc file not found

- LINUX.md
- WINDOWS.md
- _partials/ubuntu_spark.md
- macOS.md
> bump spark version from 3.5.2 to 3.5.3

- LINUX.md
- WINDOWS.md
- _partials/ubuntu_spark.md
- macOS.md
Spark bump from 3.5.2 to 3.5.3
> Minor changes to spark section

- LINUX.md
- WINDOWS.md
- _partials/repo_overview.md
- _partials/ubuntu_python.md
- _partials/ubuntu_spark.md
- macOS.md
Updated Setup for Data Engineering Challenge + Solution migration from Python 3.8.14 to Python 3.12.8.
Companion PR's:
- lewagon/data-engineering-solutions#629 
- lewagon/data-engineering-meta#114
- Misc typo's and language corrections
- Added more context to a successful spark install
- Added more context to adding direnv zsh plugin
> Updated for python 3.8.14 --> 3.12.8 migration

- LINUX.md
- WINDOWS.md
- _partials/cli_tools.md
- _partials/dotfiles_new_laptop.md
- _partials/terraform.md
- _partials/ubuntu_python.md
- _partials/ubuntu_spark.md
- macOS.md
Fixes for some small bugs:
- [Remove double curl in apt install](https://github.com/lewagon/data-engineering-setup/commit/3a53e19ea85095eee0645f05e90be8d9c1977937)
- [Output terraform gpg download to dev null](https://github.com/lewagon/data-engineering-setup/commit/1e993f6714135d19d32b6d9fe411212552adb095) 
- [No need to quit terminal windows](https://github.com/lewagon/data-engineering-setup/commit/3772b07c93edc9279c9cb21558c4bb4c56dba129)
- [Streamline spark installation](https://github.com/lewagon/data-engineering-setup/commit/262a1a326e0077805f4b672c40dd0876f303ce08) 
- [Split the pip upgrade and pipx installation](https://github.com/lewagon/data-engineering-setup/commit/e74c8f2e086055bda33abdd70630d279a96a5d8f)
> Minor fixes
